src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventsRepository::class)]
class Events
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_time = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 200, nullable: true)]
    private ?string $image = null;

    #[ORM\Column]
    private ?int $capacity = null;

    #[ORM\Column(length: 150)]
    private ?string $contact_email = null;

    #[ORM\Column(length: 15, nullable: true)]
    private ?string $contact_phone = null;

    #[ORM\Column(length: 150)]
    private ?string $street_name = null;

    #[ORM\Column(length: 15)]
    private ?string $street_number = null;

    #[ORM\Column(length: 15)]
    private ?string $zipcode = null;

    #[ORM\Column(length: 50)]
    private ?string $city = null;

    #[ORM\Column(length: 150)]
    private ?string $country = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $link = null;

    #[ORM\Column(length: 50)]
    private ?string $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->date_time;
    }

    public function setDateTime(\DateTimeInterface $date_time): static
    {
        $this->date_time = $date_time;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): static
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getContactEmail(): ?string
    {
        return $this->contact_email;
    }

    public function setContactEmail(string $contact_email): static
    {
        $this->contact_email = $contact_email;

        return $this;
    }

    public function getContactPhone(): ?string
    {
        return $this->contact_phone;
    }

    public function setContactPhone(?string $contact_phone): static
    {
        $this->contact_phone = $contact_phone;

        return $this;
    }

    public function getStreetName(): ?string
    {
        return $this->street_name;
    }

    public function setStreetName(string $street_name): static
    {
        $this->street_name = $street_name;

        return $this;
    }

    public function getStreetNumber(): ?string
    {
        return $this->street_number;
    }

    public function setStreetNumber(string $street_number): static
    {
        $this->street_number = $street_number;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): static
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): static
    {
        $this->link = $link;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Form/EventsType.php
<?php

namespace App\Form;

use App\Entity\Events;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', null, [
                "attr" => [
                    "placeholder"=>"Name of the Event", 
                    "class"=>"input-box"
                    ]])
        
            ->add('date_time', null, [
                'widget' => 'single_text',
                'label' => 'Date & Time ',
                "attr" => [
                    "class"=>"input-box",
                    ]])

            ->add('description',null, [
                "attr" => [
                    "placeholder"=>"What is the event about?", 
                    "class"=>"input-box"
                    ]])

            ->add('image',null, [
                "attr" => [
                    "placeholder"=>"Enter the image link", 
                    "class"=>"input-box"
                    ]])

            ->add('capacity',null, [
                'label' => 'Max Capacity',
                "attr" => [
                    "placeholder"=>"Name of the Event", 
                    "class"=>"input-box"
                    ]])
            ->add('contact_email', EmailType::class, [
                'label' => 'Email to contact the event',
                "attr" => [
                    "placeholder"=>"Enter the contact email", 
                    "class"=>"input-box"
                    ]])
            ->add('contact_phone',null, [
                'label' => 'Phone No. to contact the event',
                "attr" => [
                    "placeholder"=>"Enter the contact phone number", 
                    "class"=>"input-box"
                    ]])
            ->add('street_name',null, [
                'label' => 'Address / Street Name',
                "attr" => [
                    "placeholder"=>"Enter the street name", 
                    "class"=>"input-box"
                    ]])
            ->add('street_number',null, [
                'label' => 'Address / Street Number',
                "attr" => [
                    "placeholder"=>"Enter the street number", 
                    "class"=>"input-box"
                    ]])
            ->add('zipcode',null, [
                'label' => 'Address / Zipcode',
                "attr" => [
                    "placeholder"=>"Enter the Zipcode", 
                    "class"=>"input-box"
                    ]])
            ->add('city',null, [
                "attr" => [
                    "placeholder"=>"Enter the City of the Event", 
                    "class"=>"input-box"
                    ]])
            ->add('country',null, [
                "attr" => [
                    "placeholder"=>"Enter the Country of the Event", 
                    "class"=>"input-box"
                    ]])
            ->add('link',null, [
                "attr" => [
                    "placeholder"=>"Enter the Link to the Event", 
                    "class"=>"input-box"
                    ]])
            ->add('category',ChoiceType::class, [
                'label' => 'Select the Events Category',
                'choices'  => [
                    'Concert' => 'Concert',
                    'Festival' => 'Festival',
                    'Party' => 'Party',
                    'Performing Arts' => 'Performing Arts',
                    'Food & Drink' => 'Food and Drink',
                ], 
                "attr" => [
                    "class"=>"input-box"
                ]])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Events::class,
        ]);
    }
}

src/Controller/EventsController.php
<?php

namespace App\Controller;

use App\Entity\Events;
use App\Form\EventsType;
use App\Repository\EventsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/events')]
class EventsController extends AbstractController
{
    #[Route('/', name: 'app_events_index', methods: ['GET'])]
    public function index(EventsRepository $eventsRepository): Response
    {
        return $this->render('events/index.html.twig', [
            'events' => $eventsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_events_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $event = new Events();
        $form = $this->createForm(EventsType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('app_events_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('events/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_events_show', methods: ['GET'])]
    public function show(Events $event): Response
    {
        return $this->render('events/show.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_events_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Events $event, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EventsType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_events_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('events/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_events_delete', methods: ['POST'])]
    public function delete(Request $request, Events $event, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_events_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/filter/{category}', name: 'app_events_filter', methods: ['GET'])]
    public function filterByCategory(EventsRepository $eventsRepository, $category ): Response
    {

        $category = str_replace('-', ' ', $category);
        $category = urldecode($category);

        $events = $eventsRepository->findByCategory($category);

        return $this->render('events/filter.html.twig', [
            'events' => $events,
            'category' => $category,
        ]);
    }

    #[Route('/search/{events}', name: 'app_events_search', methods: ['GET'])]
    public function searchEvent(EventsRepository $eventsRepository, $category ): Response
    {

        $category = str_replace('-', ' ', $category);
       
        $events = $eventsRepository->findByCategory($category);

        return $this->render('events/filter.html.twig', [
            'events' => $events,
            'category' => $category,
        ]);
    }
}

templates/events/_delete_form.html.twig
<form method="post" action="{{ path('app_events_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button type="submit" class="myButton"><i class='bx bxs-trash' ></i> Delete</button>
</form>

templates/events/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="myButton">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/events/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Event
{% endblock %}

{% block body %}

	{% include 'components/navbar.html.twig' %}

	<div class="myForm">
		<div class="formContainer">
			<h1 style="text-align: center;">EDIT EVENT</h1>		
							
			{{ include('events/_form.html.twig', {'button_label': 'Update'}) }}
			<a class="myButton" href="{{ path('app_events_index') }}"><i class='bx bx-arrow-back'></i> Back</a>
			{{ include('events/_delete_form.html.twig') }}

		</div>
	</div>

	{% include 'components/footer.html.twig' %}

{% endblock %}

templates/events/filter.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ category|title }} Events
{% endblock %}


{% block body %}

	{% include 'components/navbar.html.twig' %}

	<h1 style="color: #ff19be; text-align: center;">{{ category|upper }} EVENTS</h1>
    
    <div class="myGrid">

	{% for event in events %}

		

			<div class='myCard' style='background-image: url("{{ event.image }}");'>
				<div class='myCardTitle'>
					<h1>{{ event.name }}</h1>
				</div>
				<div class='myCardContent'>
					<p><i class='bx bx-calendar'></i>
						
						<span>{{ event.dateTime ? event.dateTime|date('Y-m-d H:i:s') : '' }}</span>
					</p>
					<p><i class='bx bxs-map'></i>
						<span>{{ event.city }},
							{{ event.country }}</span>
					</p>
					<p><i class='bx bxs-category' ></i>
							<span>{{ event.category }}</span>
						</p>
					</p>
				</div>
				<div class='myCardBotones'>
					
						<a class="myButton" href="{{ path('app_events_show', {'id': event.id}) }}">Details</a>
						<a class="myButton" href="{{ path('app_events_edit', {'id': event.id}) }}">Update</a>
					
				</div>
			</div>
		

	{% else %}
		<h5 style="color: #fcf5fa;">No records found...</h5>
	{% endfor %}

	</div>

{% include 'components/footer.html.twig' %}
{% endblock %}

templates/events/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}All Events
{% endblock %}


{% block body %}

	{% include 'components/navbar.html.twig' %}

	<h1 style="color: #ff19be; text-align: center;">ALL EVENTS</h1>
    
    <div class="myGrid">

	{% for event in events %}

		

			<div class='myCard' style='background-image: url("{{ event.image }}");'>
				<div class='myCardTitle'>
					<h1>{{ event.name }}</h1>
				</div>
				<div class='myCardContent'>
					<p><i class='bx bx-calendar'></i>
						
						<span>{{ event.dateTime ? event.dateTime|date('Y-m-d H:i:s') : '' }}</span>
					</p>
					<p><i class='bx bxs-map'></i>
						<span>{{ event.city }},
							{{ event.country }}</span>
					</p>
					<p><i class='bx bxs-category' ></i>
							<span>{{ event.category }}</span>
						</p>
					</p>
				</div>
				<div class='myCardBotones'>
					
						<a class="myButton" href="{{ path('app_events_show', {'id': event.id}) }}">Details</a>
						<a class="myButton" href="{{ path('app_events_edit', {'id': event.id}) }}">Update</a>
					
				</div>
			</div>
		

	{% else %}
		<h5 style="color: #fcf5fa;">No records found...</h5>
	{% endfor %}

	</div>

{% include 'components/footer.html.twig' %}
{% endblock %}

templates/events/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create Event
{% endblock %}

{% block body %}

	{% include 'components/navbar.html.twig' %}

	<div class="myForm">
		<div class="formContainer">
			<h1 style="text-align: center">CREATE NEW EVENT</h1>
			{{ include("events/_form.html.twig") }}

			<a class="myButton" href="{{ path('app_events_index') }}">back to events</a>
		</div>
	</div>

	{% include 'components/footer.html.twig' %}

{% endblock %}

templates/events/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Details
{% endblock %}

{% block body %}

	{% include 'components/navbar.html.twig' %}

	<div class="details" style='background-image: url("{{ event.image }}");'>

		<div class="event-name">
			<h1>{{ event.name }}</h1>
		</div>

		<div class="details-content">
            <p>
				<i class='bx bxs-category' ></i>
				<span>{{ event.category }}</p>
			</p>
			<p>
				<i class='bx bx-calendar'></i>
				<span>
					<span>{{ event.dateTime ? event.dateTime|date('Y-m-d H:i:s') : '' }}</span>
				</p>
			</p>
			<p>
				<i class='bx bxs-map'></i>
				<span>{{ event.city }},
					{{ event.country }}</p>
			</p>
			<p>
				<i class='bx bx-home-heart'></i>
				<span>{{ event.streetName }}
					{{ event.streetNumber }},
					{{ event.zipcode }}</span>
			</p>
			<p>
				<i class='bx bx-link' ></i>
				<span><a href="{{ event.link }}">Go to the event's website</a>
			</p>
            <p>
				<i class='bx bxs-envelope' ></i>
				<span>{{ event.contactEmail }}</p>
			</p>
            <p>
				<i class='bx bxs-phone' ></i>
				<span>{{ event.contactPhone }}</p>
			</p>
			<p>
				<i class='bx bxs-hand-right'></i>
				<span>{{ event.description }}</span>
			</p>
            
		</div>

		<div class='detailsBotones'>
			<a class="myButton" ; href="{{ path('app_events_index') }}"><i class='bx bx-arrow-back'></i> Back</a>	
			<a class="myButton" ; href="{{ path('app_events_edit', {'id': event.id}) }}"><i class='bx bx-upload'></i> Update</a>
			{{ include('events/_delete_form.html.twig') }}
            
			

		</div>

	</div>

{% endblock %}